# Generated by Django 6.0.5 on 2026-05-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OVERFLOW', 'Overflowing Bin'), ('MISSED_PICKUP', 'Missed Pickup'), ('ILLEGAL_DUMP', 'Illegal Dumping'), ('HAZARDOUS', 'Hazardous Waste')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_reports', to='locations.cell')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to='locations.sector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
